backend:
  name: github
  repo: KiwiDev808/sou-cesta-solidaria
  branch: main
  base_url: https://sou-cesta-solidaria.vercel.app
  auth_endpoint: api/auth

show_preview_links: false
locale: 'pt'
site_url: https://sou-cesta-solidaria.vercel.app

publish_mode: editorial_workflow
media_folder: public/uploads
public_folder: /uploads
collections:
  - name: 'config'
    label: 'Config'
    delete: false
    files:
      - label: 'Tipo de fatura'
        name: 'invoice_types'
        file: 'config/invoice_types.json'
        allow_add: true
        fields:
          - label: Tipo de fatura
            name: invoice_types
            widget: list
            allow_add: true
            fields:
              - label: tipo
                name: type
                widget: string

      - label: 'Tamanho de cesta'
        name: 'basket_sizes'
        allow_add: true
        file: 'config/basket_sizes.json'
        fields:
          - label: Tamanho de Cesta
            name: basket_sizes
            widget: list
            allow_add: true
            fields:
              - label: tamanho
                name: size
                widget: 'string'

      - label: 'Tipo de Cesta'
        name: 'basket_types'
        allow_add: true
        file: 'config/basket_types.json'
        fields:
          - label: Tipo de Cesta
            name: basket_types
            widget: list
            allow_add: true
            fields:
              - label: tipo
                name: type
                widget: 'string'

  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Cats'
            name: 'cats'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }

  - name: 'products'
    label: 'Produtos'
    label_singular: 'Produto'
    identifier_field: type
    create: true
    folder: 'content/products'
    summary: '{{title}}-{{type}} -- {{year}}/{{month}}/{{day}}'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Nome', name: 'title', widget: 'string' }
      - { label: 'Tipo', name: 'type', widget: 'string' }
      - {
          label: 'Imagem de Capa',
          name: 'image',
          widget: 'image',
          required: true,
        }
      - { label: 'Preço', name: 'price', widget: 'number' }
      - { label: 'Link da Compra', name: 'url', widget: 'string' }
      - {
          label: 'Tipo de Fatura',
          name: 'invoice_type',
          widget: 'relation',
          collection: 'config',
          file: 'invoice_types',
          search_fields: [invoice_types.*.type],
          value_field: invoice_types.*.type,
          display_fields: [invoice_types.*.type],
        }

  - name: 'Media'
    label: 'Imprensa'
    folder: 'content/media'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - {
          label: 'Imagem de Capa',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - { label: 'Link', name: 'url', widget: 'string', hint: 'Link .' }
      - {
          required: true,
          label: 'Data',
          name: 'date',
          widget: 'datetime',
          date_format: 'DD.MM.YYYY',
          time_format: 'HH:mm',
        }

  - name: 'questions'
    label: 'Perguntas Frequentes'
    label_singular: 'Pergunta'
    folder: 'content/questions'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Pergunta', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Resposta', name: 'body', widget: 'text' }
