backend:
  name: github
  repo: KiwiDev808/sou-cesta-solidaria
  branch: test/netlify-cms
  base_url: https://sou-cesta-solidaria-teste.vercel.app
  auth_endpoint: api/auth

media_folder: public/uploads
public_folder: /uploads
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Cats'
            name: 'cats'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }

  - name: 'Products'
    label: 'Produtos'
    folder: 'content/products'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - {
          label: 'Quantidade',
          name: 'quantity',
          value_type: 'float',
          widget: 'number',
        }
      - { label: 'Imagem', name: 'thumbnail', widget: 'image' }
      - { label: 'Preço', name: 'price', widget: 'number' }
      - { label: 'Link', name: 'url', widget: 'string' }

  - name: 'Media'
    label: 'Imprensa'
    folder: 'content/media'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Imagem', name: 'thumbnail', widget: 'image' }
      - { label: 'Link', name: 'url', widget: 'string' }

  - name: 'Frequent Questions'
    label: 'Perguntas Frequentes'
    folder: 'content/questions'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Descrição', name: 'description', widget: 'string' }
